### ISSUE TITLE
Dark mode adjustments

### ISSUE THREAD

**Issue by linaseiche** [Hakenadu/bitcoinations#17]
Please make adjustments as follows:

Make hyperlink text on country pop-ups white
<img width="402" alt="Screen Shot 2021-06-21 at 12 26 38 AM" src="https://user-images.githubusercontent.com/86118677/122681677-24089880-d228-11eb-98ae-d806743b84a4.png">

Make country borders in dark mode light grey instead of white, and make country fill colors slightly darker
<img width="920" alt="Screen Shot 2021-06-21 at 12 28 39 AM" src="https://user-images.githubusercontent.com/86118677/122681699-384c9580-d228-11eb-861a-eb77b6bb9c75.png">

Make the table menu background (Country, Legal Tender etc) slightly lighter to achieve higher contrast with background
<img width="523" alt="Screen Shot 2021-06-21 at 12 30 36 AM" src="https://user-images.githubusercontent.com/86118677/122681710-469ab180-d228-11eb-856b-fe5a6de07394.png">

**Comment by Hakenadu** [comment]
done and deployed
