### ISSUE TITLE
Adjust decimal places of bitcoin holdings

### ISSUE THREAD

**Issue by linaseiche** [Hakenadu/bitcoinations#18]
Hide decimal places for bitcoin holdings (eg. 213,519 instead of 213,519.00)
<img width="120" alt="Screen Shot 2021-06-21 at 12 31 52 AM" src="https://user-images.githubusercontent.com/86118677/122681779-a2fdd100-d228-11eb-800d-9f8580c88eeb.png">

**Comment by ChristopherDicke** [comment]
Was ist wenn 1 btc mal 360k wert ist ? (ist ja das Preisziel der Commerzbank) Schweden hat ja auch letztens mal 0,6 verkauft

**Comment by Hakenadu** [comment]
feature not a bug
