### ISSUE TITLE
Change font to Roboto

### ISSUE THREAD

**Issue by linaseiche** [Hakenadu/bitcoinations#9]
Change all current website text to Roboto.

For the column categories on the main chart (Nation, Legal Tender, Holdings, Sources etc), increase the font size to be larger than the column entries, and make the categories bold

**Comment by ChristopherDicke** [comment]
Ist das nicht schon roboto ?

**Comment by ChristopherDicke** [comment]
![grafik](https://user-images.githubusercontent.com/2652914/122650341-9d25c400-d132-11eb-9d3f-e5c5a49ca8b9.png)

**Comment by linaseiche** [comment]
Display-Schriftart scheint aber Helvetica Neue zu sein

**Comment by Hakenadu** [comment]
done and deployed
